{% set name = "setuptools-github" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b5a783d3e3e915259b18bd9dd237c1282638377c074c17461303d4cf7f09f4f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - jinja2
    - typing_extensions
    - mypy_extensions
  run:
    - python >=3.8
    - setuptools
    - jinja2
    - typing_extensions
    - mypy_extensions

test:
  requires:
    - pip
    - pytest
    - setuptools
    - mypy_extensions
    - git
    - pygit2
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/cav71/setuptools-github
  license: BSD-2-Clause
  license_family: BSD
  summary: Supports github releases
  license_file: LICENSE
  description: |
    Follow a well defined github release process

extra:
  recipe-maintainers:
    - cav71
