{% set name = "setuptools-github" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24d3c3156ea3eb379f53a91e9d72a1b437fb7550a9fc30dccc5fccc8e76cb095

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jinja2
    - typing_extensions
    - mypy_extensions
  run:
    - python >={{ python_min }}
    - setuptools
    - jinja2
    - typing_extensions
    - mypy_extensions

test:
  requires:
    - pip
    - pytest
    - setuptools
    - mypy_extensions
    - git
    - pygit2
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/cav71/setuptools-github
  license: BSD-2-Clause
  license_family: BSD
  summary: Supports github releases
  license_file: LICENSE
  description: |
    Follow a well defined github release process

extra:
  recipe-maintainers:
    - cav71
