{% set name = "setuptools-github" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9465b0a72f5c7c5d32df3cb378c192f81dcb820f36241b1632ef3f7566f86f59

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools
    - mypy_extensions

test:
  requires:
    - pip
    - pytest
    - setuptools
    - mypy_extensions
    - git
    - pygit2
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/cav71/setuptools-github
  license: BSD-2-Clause
  license_family: BSD
  summary: Supports github releases
  license_file: LICENSE
  description: |
    Follow a well defined github release process

extra:
  recipe-maintainers:
    - cav71
