{% set name = "setuptools-github" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cdf9e88a72ee77ef721c0dcc64cb21a17c4ead1f691e5d5df03a61418557630

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

test:
  requires:
    - pip
    - pytest
    - setuptools
    - mypy_extensions
    - git
    - pygit2
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/cav71/setuptools-github
  license: BSD-2-Clause
  license_family: BSD
  summary: Supports github releases
  license_file: LICENSE
  description: |
    Follow a well defined github release process

extra:
  recipe-maintainers:
    - cav71
